
POST {{hostname}}/auth/signup
Content-Type: application/json
x-api-key: 0145fa99e83bbe3d50ebbb96131b23ff21c2cba6710010248561396385640b99de9ca29037af8e1ab5fd30dcff89a3498bf8ef9cddc84a49625dd6a34392da9d

{
    "name": "MVT",
    "email": "mthang1801@gmail.com",
    "password": "Aa@123456"
}

###

POST {{hostname}}/auth/login
Content-Type: application/json
x-api-key: 0145fa99e83bbe3d50ebbb96131b23ff21c2cba6710010248561396385640b99de9ca29037af8e1ab5fd30dcff89a3498bf8ef9cddc84a49625dd6a34392da9d

{   
    "email": "mthang1801@gmail.com",
    "password": "Aa@123456",
    "refreshToken" : ""
}

### 

POST {{hostname}}/auth/logout
x-api-key: 0145fa99e83bbe3d50ebbb96131b23ff21c2cba6710010248561396385640b99de9ca29037af8e1ab5fd30dcff89a3498bf8ef9cddc84a49625dd6a34392da9d
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM2ZTRlN2Q3NzIxMWE1NTJlNzIzY2MiLCJlbWFpbCI6Im10aGFuZzE4MDErMjJAZ21haWwuY29tIiwibmFtZSI6Ik1WVCIsInZlcmlmeSI6ZmFsc2UsInN0YXR1cyI6ImluYWN0aXZlIiwiaWF0IjoxNjgxMzk2NTcyLCJleHAiOjE2ODE1NjkzNzJ9.OP4wb3_IiujkBigUv__0cu5dmaDMJ_P35Luluf-tvn0l8KSJp9Rgo8FqPD0PUoWMSHjzY_2UxfwrpinNVOQsyNDSvXNKS1bLlVXUhrZv5Mio9HcSbvKu3cHoKGBO_mqdbYAGTgKzk4U4b325YHB-l_YCm9uA3fvL1fc858YdGQ6FjZerAAgmogA8BqU3_ZUKqTmH_PybofewYUL7LFXWjK0Gd1ktvttldy-bB2KX7T6hkuLUVC3ywa6alerYUeVGafxDdEPQR9A0hVCTPvaO1quDu1BGDqELg5IDh7480d4iqxR4z-4Doz-IVVsal9FCWaIYMQkwwFEgO8fjGtOJbbve1E9BNaWXwh_ZerEgHJVBMBQuq0hivPonCQunq6X-I3ZeQ_NA8SappmZew4Y4DMXIQKTuJeMhNqMqxHzmnnY4Jlb7maXQEBemt7yhFFwpfZwMyZ_vnAbPPF_rTGoDszCj53lB-f3xkrHSeWYF3MbPFynbnV4DqSvIsm_vn0nXcXMlcejjigx1TXaKTRxWlmPCrnb0N0fuO1dZIgbw89Sb4WrXK-Cp1dLCCQIN4cf_ECb-CxMbt73kKD8pUWijbWE-MhGnQKUfhipnrOKzyxvDpFKA0P4oW-i6MkBa1AENo3um4uwxuNTfzf5U5L4J4iw_n1qp55AZOUGDtPGCnzY
x-client-id: 6436e4e7d77211a552e723cc

### 

POST {{hostname}}/auth/handler-refresh-token
Content-Type: application/json
x-api-key: 0145fa99e83bbe3d50ebbb96131b23ff21c2cba6710010248561396385640b99de9ca29037af8e1ab5fd30dcff89a3498bf8ef9cddc84a49625dd6a34392da9d
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM4MjNiOWY3NWM0MmI2MzZjYWQxMWEiLCJlbWFpbCI6Im10aGFuZzE4MDFAZ21haWwuY29tIiwibmFtZSI6Ik1WVCIsInZlcmlmeSI6ZmFsc2UsInN0YXR1cyI6ImluYWN0aXZlIiwiaWF0IjoxNjgxNDAzMTI2LCJleHAiOjE2ODE1NzU5MjZ9.Kz5YXewcIjPE1Ur22cZJXlbq3hLsLmkeDN9oPaUHVgcKqElmtdjd9pP2Hjp-IU432bI7FHQDbryO8Ge_pCIQzpcWsoLM5L0cW70F2sokXRv0ODWGo62QHCR6ABQ-Dg8kUvQx37VjrfYjsfPB1Q1vOUYuAIidye12OVwQsloyHUTJdXISSv-tiOFWSBXSWqJlWVPzd7FR-JD8TNCx7XrWZmiegOO789jch4WmKRDZhDuctwXsmoOpvhZ-YeGhzDa34y-8poRmAQSV8eHeH7-BOssG-g8tUZLrxsBN6tt5ycJUvKum5GGnC1Rx3rRQZAyWpEiLQJ6gaMO3xjtnSJTUxok2nxMKo7K4LSpRqVzIb2v2pESDYVufBXDgsdsz7kXVDQQIn60bbtRVpXn_7_dJ3Nl6ZvmVBY1KO-aq36EwDQgNiEL81R02NULM2PUv-3TbbTnZmQB5gficUPon4lZfXnrZ-y1ns_9UD3rNoOeDPkqCc_6MIplkSyL2sTip_tkn7oxELERt3Xhyp6YLu6vwfpCYyCJ30f-E6xg_Nq9iuWz2Onq8CS6GyhDxNKYQOxUlYc54HtWaCMRXJppOsuJq6Cyasf_aUWX2mGAXAf8x8dhSrSzfvspN0khxDrypzSZZe0HXn9GgPFsvyEWLWLlFrL9rs35TW_Tmc0hRT-CY9cg
x-client-id: 643823b9f75c42b636cad11a
refresh-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM4MjNiOWY3NWM0MmI2MzZjYWQxMWEiLCJlbWFpbCI6Im10aGFuZzE4MDFAZ21haWwuY29tIiwibmFtZSI6Ik1WVCIsInZlcmlmeSI6ZmFsc2UsInN0YXR1cyI6ImluYWN0aXZlIiwiaWF0IjoxNjgxNDAzMTI2LCJleHAiOjE2ODIwMDc5MjZ9.oDVmiU99WqQTeBWka2l1G2DsvCGVeDpYOW2tsi-6GwLmNfB9_dtPmwQXRVLQQ2TEj0FPTO9azPeS7RqL9jFb6ZHWuNiInMPnTVuxaTEsdVa6aqO_dZd0BWBMMowvpAssLomZYmgYBnOSYpOPzAv96uSrcnYgwlWIkbZ0Gwk6BF8YSdPcuk3lfFHo6rprrQh9ddV2OL3rw5k_6GaI5YEl8MjzUJUedAfUjeBhiBS76qutfa4hMjBkX7O5YR9-2uD5N7tJbqAwm6ujiZKLY5dUxGO6GxU1yAciXKc3MvWff-aw-8j7jf3oKKn4wbgEt0FPYCwMgZG1NNgT6XvihgPAq6DFKwf_YK4KDRZ_oXt5eqsDjU72akksH4Bu-4ufZJbYSyIKSkHiZ6K9Nr86gfWO3NaZApESBiWGGf9LXMcsOuFqt38x6_Ka5XBM1mzDnU04zI1yqffOpgRUTEiVKEEWeFRXFpFB723Oc-tuHLhZgbGvUxhrImbG3GyjrX1qb8H7eDeAQPpBOYJD28vXmcJAaBLMbMG_AXp9QkQbuRun3KfvLohFUuBWcx641qohIvv2CH0ZJCgV3k_85JnKz2MYU2yPXJjFTCQQaZ0AMGVgJnv6Qs16NakMv5D-brvEAw7DTrBtQRcE4S_HhrqToCy7nimxd4Z4sbKBuvJQr8_m_F4

